# This file was initially generated by dredger, but feel free to adapt it to your needs and environment
set dotenv-load
program := `basename $PWD`
port := env_var_or_default("PORT", "9090")

help:
    just -l

templ:
    templ generate web/pages/*.templ

build: templ
	go mod tidy
	go build

install: build
	go install

run: build
    go run . -p {{port}}

debug: build
    go run . -d -p {{port}}

generate:
	dredger generate OpenAPI.yaml -o . -f -n dredger-todos

sbom-build:
	GOARCH=amd64 GOOS=linux cyclonedx-gomod mod -licenses -json -output sbom.json

sbom: sbom-build
	curl -X "POST" "http://dependency-track-api.${DEPENDENCY_TRACK_SERVER}/api/v1/bom" \
		-H "Content-Type:multipart/form-data" \
		-H "X-Api-Key:${DEPENDENCY_TRACK}" \
		-F "projectName={{program}}/dredger-todos" \
		-F "bom=@sbom.json"

docker-build:
	env GOOS=linux GOARCH=amd64 go build && \
	docker build -t dredger-todos . && \
	rm -rf dredger-todos

docker-run:
	docker run --rm -p 8080:8080 --env-file=.env dredger-todos

required:
    go install github.com/a-h/templ/cmd/templ@latest

# List all ToDo items of the source code
todo:
    rg -ip "to.?do:"

# push to git
push:
    git add .
    git commit -a
    git push

# changes for git
status:
    git status -s

pull:
    git pull
