# This file was initially generated by dredger, but feel free to adapt it to your needs and environment
set dotenv-load
program := `basename $PWD`
port := env_var_or_default("TODOS_PORT", "9090")
sessionkey := env_var_or_default("TODOS_SESSION_KEY", "safe")

help:
    just -l

templ:
    templ generate web/pages/*.templ

build: templ
	go mod tidy
	go build

install: build
	go install

run: build
    TODOS_SESSION_KEY={{sessionkey}} go run . -p {{port}}

generate:
	dredger generate -o . -n {{program}}

sbom-build:
	GOARCH=amd64 GOOS=linux cyclonedx-gomod app -output linux-amd64.bom.xml

sbom: sbom-build
	curl -X "POST" "http://dependency-track-api.${DEPENDENCY_TRACK_SERVER}/api/v1/bom" \
		-H "Content-Type:multipart/form-data" \
		-H "X-Api-Key:${DEPENDENCY_TRACK}" \
		-F "projectName={{program}}/todos" \
		-F "bom=@linux-amd64.bom.xml"

docker-build:
	env GOOS=linux GOARCH=amd64 go build && \
	docker build -t todos . && \
	rm -rf todos

docker-run:
	docker run --rm -p 8080:8080 --env-file=.env todos

required:
    go install github.com/a-h/templ/cmd/templ@latest

# List all ToDo items of the source code
todo:
    rg -ip "to.?do:"

# push to git
push:
    git add .
    git commit -a
    git push

# changes for git
status:
    git status -s
