// Don't edit this file, as it is generated by dredger
package main

import (
	"context"
	"embed"
	"todos/core"
	"todos/core/log"
	"todos/core/tracing"
	"todos/rest"
	"todos/rest/middleware"
	"todos/web"

	"github.com/labstack/echo/v4"
	echoMiddleware "github.com/labstack/echo/v4/middleware"
	// "go.opentelemetry.io/contrib/instrumentation/github.com/labstack/echo/otelecho"
)

//go:embed web
var embeddedFS embed.FS

func main() {
	// ToDo: Add vasic command line options as _-n_/_-name_ and _-d_/_-debug_ using flags

	log.Info().Str("svc", core.AppConfig.Service).Msg("Starting service")

	// init Opentelemetry
	if core.AppConfig.Tracing {
		tp, err := tracing.InitTracer()
		if err != nil {
			log.Fatal().Err(err).Msg("Initializing tracer failed")
		}
		defer func() {
			if err := tp.Shutdown(context.Background()); err != nil {
				log.Warn().Err(err).Msg("Error shutting down tracer provider")
			}
		}()
	}

	// start echo server
	e := echo.New()
	e.Use(echoMiddleware.CORS())
	e.Use(echoMiddleware.Logger())
	// e.Use(otelecho.Middleware(core.AppConfig.Sid))
	e.Use(middleware.PolicyHandler) // Policy Enforcement Point to check access

	rest.NewHandler(e)

	// serve doc
	e.FileFS("/doc", "web/doc/index.html", embeddedFS)
	e.FileFS("/OpenAPI.yaml", "web/doc/OpenAPI.yaml", embeddedFS)
	// serve default stylesheets and javascript files
	e.StaticFS("/css/", echo.MustSubFS(web.Css, "css"))
	e.StaticFS("/js/", echo.MustSubFS(web.Js, "js"))
	e.StaticFS("/", echo.MustSubFS(web.Public, "public"))

	if core.AppConfig.CertPem != "" && core.AppConfig.KeyPem != "" {
		e.Logger.Fatal(e.StartTLS(":"+core.AppConfig.Port, []byte(core.AppConfig.CertPem), []byte(core.AppConfig.KeyPem)))
	} else {
		e.Logger.Fatal(e.Start(":" + core.AppConfig.Port))
	}
}
