// Don't edit this file, as it is generated by dredger
package async

import (
	"dredgerTodos/async/subscribers"
	"dredgerTodos/core/log"

	"github.com/labstack/echo/v4"
	"github.com/nats-io/nats.go"
)

// Subscribe to NATS topics
var subscriptions []*nats.Subscription
var NC *nats.Conn

// RegisterHandlers sets up Echo routes including WebSocket
func RegisterHandlers(e *echo.Echo) error {
	// Connect to NATS
	var err error
	NC, err = nats.Connect(nats.DefaultURL)
	if err != nil {
		log.Error().Err(err).Msg("Failed to connect to NATS")
		return err
	}
	log.Info().Str("url", nats.DefaultURL).Msg("Connected to NATS")

	receiveAddToDosub := subscribers.ReceiveAddToDo(NC)
	if receiveAddToDosub == nil {
		log.Error().Msg("Subscription to todos failed")
		return nil
	}
	subscriptions = append(subscriptions, receiveAddToDosub)

	receiveDeleteToDosub := subscribers.ReceiveDeleteToDo(NC)
	if receiveDeleteToDosub == nil {
		log.Error().Msg("Subscription to todos failed")
		return nil
	}
	subscriptions = append(subscriptions, receiveDeleteToDosub)

	receiveDoneToDosub := subscribers.ReceiveDoneToDo(NC)
	if receiveDoneToDosub == nil {
		log.Error().Msg("Subscription to todos failed")
		return nil
	}
	subscriptions = append(subscriptions, receiveDoneToDosub)

	return nil
}

func DeregisterHandlers() {
	for _, sub := range subscriptions {
		sub.Unsubscribe()
	}
	NC.Close()
}
