// Don't edit this file, as it is generated by dredger
package server

import (
	"dredgerTodos/entities"
	"encoding/json"
	"log"

	"github.com/gorilla/websocket"
	"github.com/nats-io/nats.go"
)

func Receiveaddtodo(nc *nats.Conn, ws *websocket.Conn) *nats.Subscription {

	// Subscribe to "todos"
	Sub, err := nc.Subscribe("todos", func(msg *nats.Msg) {
		envtoDo := entities.Envelope{
			Type: "toDo",
			Data: msg.Data,
		}
		outtoDo, err := json.Marshal(envtoDo)
		if err != nil {
			log.Println("Error marshaling toDo envelope:", err)
			return
		}
		if writeErr := ws.WriteMessage(websocket.TextMessage, outtoDo); writeErr != nil {
			log.Println("Error writing toDo to WebSocket:", writeErr)
		}

	})
	if err != nil {
		log.Println("NATS subscribe to todos failed:", err)
		return nil
	}

	return Sub
}

func Receivedeletetodo(nc *nats.Conn, ws *websocket.Conn) *nats.Subscription {

	// Subscribe to "todos"
	Sub, err := nc.Subscribe("todos", func(msg *nats.Msg) {
		envid := entities.Envelope{
			Type: "id",
			Data: msg.Data,
		}
		outid, err := json.Marshal(envid)
		if err != nil {
			log.Println("Error marshaling id envelope:", err)
			return
		}
		if writeErr := ws.WriteMessage(websocket.TextMessage, outid); writeErr != nil {
			log.Println("Error writing id to WebSocket:", writeErr)
		}

	})
	if err != nil {
		log.Println("NATS subscribe to todos failed:", err)
		return nil
	}

	return Sub
}

func Receivedonetodo(nc *nats.Conn, ws *websocket.Conn) *nats.Subscription {

	// Subscribe to "todos"
	Sub, err := nc.Subscribe("todos", func(msg *nats.Msg) {
		envid := entities.Envelope{
			Type: "id",
			Data: msg.Data,
		}
		outid, err := json.Marshal(envid)
		if err != nil {
			log.Println("Error marshaling id envelope:", err)
			return
		}
		if writeErr := ws.WriteMessage(websocket.TextMessage, outid); writeErr != nil {
			log.Println("Error writing id to WebSocket:", writeErr)
		}

	})
	if err != nil {
		log.Println("NATS subscribe to todos failed:", err)
		return nil
	}

	return Sub
}
