// Don't edit this file, as it is generated by dredger
package entities

type MsgAddToDo struct {
	Task  string `json:"Task" yaml:"Task" xml:"Task"`
	Done  bool   `json:"Done" yaml:"Done" xml:"Done"`
	Label string `json:"Label" yaml:"Label" xml:"Label"`
}
