// Don't edit this file, as it is generated by dredger
package entities

type MsgDeleteToDo struct {
	Id    int    `json:"Id" yaml:"Id" xml:"Id"`
	Label string `json:"Label" yaml:"Label" xml:"Label"`
}
