// Don't edit this file, as it is generated by dredger
package entities

type MsgId struct {
	Id       interface{} `json:"Id,omitempty" yaml:"Id,omitempty" xml:"Id,omitempty"`
	Listname interface{} `json:"Listname,omitempty" yaml:"Listname,omitempty" xml:"Listname,omitempty"`
}
