// Don't edit this file, as it is generated by dredger
package entities

type MsgToDo struct {
	Done     interface{} `json:"Done,omitempty" yaml:"Done,omitempty" xml:"Done,omitempty"`
	Listname interface{} `json:"Listname,omitempty" yaml:"Listname,omitempty" xml:"Listname,omitempty"`
	Task     interface{} `json:"Task,omitempty" yaml:"Task,omitempty" xml:"Task,omitempty"`
}
