// Don't edit this file, as it is generated by dredger
package entities

type ToDos struct {
	ToDos  map[string]ToDo `json:"toDos,omitempty" yaml:"toDos,omitempty" xml:"toDos,omitempty"`
	NextId int             `json:"nextId,omitempty" yaml:"nextId,omitempty" xml:"nextId,omitempty"`
}

func (v *ToDos) Validate() error {

	return nil
}
