// Don't edit this file, as it is generated by dredger
package entities

import (
	"fmt"
)

type ToDo struct {
	Done bool   `json:"done,omitempty" yaml:"done,omitempty" xml:"done,omitempty"`
	Task string `json:"task,omitempty" yaml:"task,omitempty" xml:"task,omitempty"`
}

func (v *ToDo) Validate() error {

	// ToDo: Improve validation of MaxLength

	if len(v.Task) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "Task")
	}

	return nil
}
