// Don't edit this file, as it is generated by dredger
package core

import (
	_ "embed"
	"strings"
)

type Info struct {
	Service string
	Name    string
	Version string
	InfoExt
}

var (
	// Version labels the release
	Version string = strings.TrimSpace(version)
	//go:embed version
	version string
	AppInfo Info
)

func init() {
	AppInfo = Info{Service: "dredgerTodos", Version: Version, Name: ""}
}
