// Don't edit this file, as it is generated by dredger
package core

type Info struct {
	Service string
	Version string
	InfoExt
}

var AppInfo Info

func init() {
	AppInfo = Info{Service: Service, Version: Version}
}
