// Don't edit this file, as it is generated by dredger
package log

import (
	"os"
	"time"

	rotatelogs "github.com/lestrrat-go/file-rotatelogs"
	"github.com/rs/zerolog"

	"dredgerTodos/core/log/logger"
)

var log logger.ZeroLog
var Trace func() *logger.MultiEvent
var Debug func() *logger.MultiEvent
var Info func() *logger.MultiEvent
var Warn func() *logger.MultiEvent
var Error func() *logger.MultiEvent
var Fatal func() *logger.MultiEvent
var Panic func() *logger.MultiEvent
var Print func(v ...interface{})
var Printf func(format string, v ...interface{})

// initial setup
func init() {
	Setup("dredgerTodos", "dredgerTodos", "", false)
}

// Setup the logger
func Setup(name string, service string, logFilename string, debug bool) {
	// the multi logger
	log = logger.ZeroLog{}

	// add console logger
	console := zerolog.New(zerolog.ConsoleWriter{Out: os.Stderr, TimeFormat: time.RFC3339}).
		With().
		Timestamp().
		Str("service", service).
		Str("name", name).
		Logger()

	// add rotating file logger optionally
	if logFilename != "" {
		log.AddLoggerWarn(&console)
		logfile, err := rotatelogs.New(
			logFilename+".%Y%m%d%H%M",
			rotatelogs.WithLinkName(logFilename),
			rotatelogs.WithMaxAge(24*time.Hour),
			rotatelogs.WithRotationTime(time.Hour),
		)
		if err != nil {
			log.Error().Str("logfile", logFilename).Err(err).Msg("can't create rotating log file")
			return
		}
		defer logfile.Close()
		logger := zerolog.New(logfile).
			With().
			Timestamp().
			Str("service", service).
			Str("name", name).
			Logger()
		if debug {
			log.AddLoggerDebug(&logger)
		} else {
			log.AddLoggerInfo(&logger)
		}
	} else {
		if debug {
			log.AddLoggerDebug(&console)
		} else {
			log.AddLoggerInfo(&console)
		}
	}
	Trace = log.Trace
	Debug = log.Debug
	Info = log.Info
	Warn = log.Warn
	Error = log.Error
	Fatal = log.Fatal
	Panic = log.Panic
	Print = log.Print
	Printf = log.Printf
}
