// Don't edit this file, as it is generated by dredger
package middleware

import (
	"dredgerTodos/core"
	"net/http"

	"github.com/labstack/echo/v4"
)

func Authz(next echo.HandlerFunc) echo.HandlerFunc {
	return func(c echo.Context) error {
		if isAuthorized(c) {
			return next(c)
		}
		return echo.NewHTTPError(http.StatusUnauthorized, "Please provide a valid API key")
	}
}

func isAuthorized(c echo.Context) bool {
	// Check API keys
	for _, key := range core.AppConfig.ApiKeys {
		if key == c.Request().Header.Get(core.AppConfig.AuthorizationHeader) {
			return true
		}
	}
	return false
}
