// Don't edit this file, as it is generated by dredger
package middleware

import (
	"dredgerTodos/core/log"

	"github.com/labstack/echo/v4"
)

// Policy Enforcement Point to validate access permission
func LoggerHandler(next echo.HandlerFunc) echo.HandlerFunc {
	return func(c echo.Context) error {
		log.Info().Str("remote_ip", c.Request().RemoteAddr).Str("host", c.Request().Host).Str("method", c.Request().Method).Str("uri", c.Request().URL.Path).Str("user_agent", c.Request().UserAgent()).Int("status", c.Response().Status).Send()
		// next handler
		return next(c)
	}
}
