// Don't edit this file, as it is generated by dredger
package subscribers

import (
	"dredgerTodos/core/log"
	"dredgerTodos/entities"
	"dredgerTodos/usecases/messages"

	"encoding/json"

	"github.com/nats-io/nats.go"
)

func ReceiveAddToDo(nc *nats.Conn) *nats.Subscription {
	// Subscribe to "todos.addtodo"
	Sub, err := nc.Subscribe("todos.addtodo", func(msg *nats.Msg) {
		var data entities.MsgAddToDo
		err := json.Unmarshal(msg.Data, &data)
		if err != nil {
			log.Error().Err(err).Msg("Unmarshalling AddToDo failded")
			return
		}
		// business logic
		messages.AddTodoMsg(data.Label, data.Task)
	})
	if err != nil {
		log.Error().Err(err).Msg("NATS subscribe to todos failed")
		return nil
	}

	return Sub
}
