// Don't edit this file, as it is generated by dredger
package subscribers

import (
	"dredgerTodos/core/log"
	"dredgerTodos/entities"
	"dredgerTodos/usecases/messages"

	"encoding/json"

	"github.com/nats-io/nats.go"
)

func ReceiveDeleteToDo(nc *nats.Conn) *nats.Subscription {
	// Subscribe to "todos.deletetodo"
	Sub, err := nc.Subscribe("todos.deletetodo", func(msg *nats.Msg) {
		var data entities.MsgDeleteToDo
		err := json.Unmarshal(msg.Data, &data)
		if err != nil {
			log.Error().Err(err).Msg("Unmarshalling DeleteToDo failded")
			return
		}
		// business logic
		messages.DeleteTodoMsg(data.Label, data.Id)
	})
	if err != nil {
		log.Error().Err(err).Msg("NATS subscribe to todos.deletetodo failed")
		return nil
	}

	return Sub
}
