// Don't edit this file, as it is generated by dredger
package subscribers

import (
	"dredgerTodos/core/log"
	"dredgerTodos/entities"
	"dredgerTodos/usecases/messages"
	"encoding/json"

	"github.com/nats-io/nats.go"
)

func ReceiveDoneToDo(nc *nats.Conn) *nats.Subscription {
	// Subscribe to "todos.donetodo"
	Sub, err := nc.Subscribe("todos.donetodo", func(msg *nats.Msg) {
		var data entities.MsgDoneToDo
		err := json.Unmarshal(msg.Data, &data)
		if err != nil {
			log.Error().Err(err).Msg("Unmarshalling DoneToDo failded")
			return
		}
		// business logic
		messages.DoneTodoMsg(data.Label, data.Id)
	})
	if err != nil {
		log.Error().Err(err).Msg("NATS subscribe to todos.donetodo failed")
		return nil
	}

	return Sub
}
