// Don't edit this file, as it is generated by dredger
package rest

import (
	"dredgerTodos/core"
	"net/http"

	"github.com/labstack/echo/v4"
)

// Returns infos about the service
func GetInfo(c echo.Context) error {
	return c.JSON(http.StatusOK, core.AppInfo)
}
