// Don't edit this file, as it is generated by dredger
package rest

import (
	"net/http"

	"github.com/labstack/echo/v4"
)

// Returns live-state of the service
func GetLive(c echo.Context) error {
	return c.String(http.StatusOK, "I'm alive.")
}
