// Don't edit this file, as it is generated by dredger
package rest

import (
	_ "embed"
	"net/http"

	"github.com/labstack/echo/v4"
)

var (
	//go:embed robots.txt
	robots string
)

// Returns robots.txt
func GetRobots(c echo.Context) error {
	return c.String(http.StatusOK, robots)
}
