// Don't edit this file, as it is generated by dredger
package rest

import (
	"dredgerTodos/sse"

	"github.com/labstack/echo/v4"
)

var HandleEvents echo.HandlerFunc

func init() {
	sse.SseServer.CreateStream("progress")
	sse.SseServer.CreateStream("notice")
	handleEventsSvc()
	HandleEvents = echo.WrapHandler(sse.SseServer)
}
