// Don't edit this file, as it is generated by dredger
package rest

import (
	"github.com/labstack/echo/v4"
	"github.com/r3labs/sse/v2"
)

var SseServer *sse.Server
var HandleEvents echo.HandlerFunc

func init() {
	SseServer = sse.New()
	SseServer.CreateStream("progress")
	HandleEvents = echo.WrapHandler(SseServer)
}
