// Don't edit this file, as it is generated by dredger
package rest

import (
	"fmt"

	"github.com/r3labs/sse/v2"
)

const bsSuccessNotice = `<div class="alert alert-success alert-dismissible fade show" role="alert">%s<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>`

func NoticeSuccessBootstrap(msg string) {
	SseServer.Publish("notice", &sse.Event{
		Event: []byte("Notice"),
		Data:  []byte(fmt.Sprintf(bsSuccessNotice, msg)),
	})
}

const bsWarningNotice = `<div class="alert alert-warning alert-dismissible fade show" role="alert">%s<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>`

func NoticeWarningBootstrap(msg string) {
	SseServer.Publish("notice", &sse.Event{
		Event: []byte("Notice"),
		Data:  []byte(fmt.Sprintf(bsWarningNotice, msg)),
	})

}

const bsErrorNotice = `<div class="alert alert-error alert-dismissible fade show" role="alert">%s<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>`

func NoticeErrorBootstrap(msg string) {
	SseServer.Publish("notice", &sse.Event{
		Event: []byte("Notice"),
		Data:  []byte(fmt.Sprintf(bsErrorNotice, msg)),
	})

}
