// Don't edit this file, as it is generated by dredger
package rest

import (
	// "dredgerTodos/rest/middleware"
	"dredgerTodos/core"
	"dredgerTodos/core/log"

	"github.com/google/uuid"
	"github.com/gorilla/sessions"
	"github.com/labstack/echo/v4"
)

var sessionStore *sessions.CookieStore

func init() {
	sessionStore = sessions.NewCookieStore([]byte(core.AppConfig.SessionKey))
}

func getSession(c echo.Context) (*sessions.Session, error) {
	session, err := sessionStore.Get(c.Request(), core.AppConfig.SessionKey)
	if err != nil || session.IsNew {
		id := uuid.Must(uuid.NewV7()).String()
		log.Info().Str("session", id).Str("id", id).Msg("New session")
		session.Values["id"] = id
		//
		// set your default session state
		//
		err = session.Save(c.Request(), c.Response())
		if err != nil {
			log.Error().Err(err).Str("session", session.Values["id"].(string)).Msg("writing session store failed")
			return nil, err
		}
	}

	return session, nil
}

func NewHandler(e *echo.Echo) {
	g := e.Group("")

	// TODO: Make a validation with openAPI sense
	// 	spec, err := middleware.ParseOpenAPISpecFile("public/OpenAPI.yaml", e.AcquireContext())
	// 	if err != nil {
	// 		e.Logger.Fatal(err)
	// 	}
	// 	g.Use(middleware.Validation(spec, e))
	//     e.HTTPErrorHandler = func(err error, c echo.Context) {
	//         switch err := err.(type) {
	//         // in case ValidationError just send the message
	//         case middleware.ValidationError:
	//             c.String(err.Status, err.Message)
	//         // in all other cases use default behavior
	//         default:
	//             e.DefaultHTTPErrorHandler(err, c)
	//         }
	//     }

	// Operations for: "/slowz"
	g.GET("/slowz", Slow)

	// Operations for: "/events"
	g.GET("/events", HandleEvents)
	// Operations for: "/events"
	g.POST("/events", HandleEvents)

	// Operations for: "/livez"
	g.GET("/livez", GetLive)

	// Operations for: "/robots.txt"
	g.GET("/robots.txt", GetRobots)

	// Operations for: "/todos/add"
	g.POST("/todos/add", AddTodo)

	// Operations for: "/readyz"
	g.GET("/readyz", GetReady)

	// Operations for: "/todos/:id"
	g.DELETE("/todos/:id", DeleteTodo)

	// Operations for: "/index.html"
	g.GET("/index.html", Index)

	// Operations for: "/slowcall"
	g.GET("/slowcall", SlowCall)

	// Operations for: "/todos/done/:id"
	g.GET("/todos/done/:id", DoneTodo)

	// Operations for: "/"
	g.GET("/", Root)

	// Operations for: "/infoz"
	g.GET("/infoz", GetInfo)

	// Operations for: "/todos"
	g.GET("/todos", Todos)

	// Call handler extensions
	newHandlerExt(e)
}
